require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
  Enabled: true

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/NumericPredicate:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
